### ISSUE TITLE
NameError: name 'selective_scan_fn' is not defined

### ISSUE THREAD

**Issue by DuHao55** [JCruan519/VM-UNet#10]
我在运行train.py时，总是报以下的错误：
![图片](https://github.com/JCruan519/VM-UNet/assets/117566234/ecde4c52-2b3b-4831-b3ad-fd71b6262841)
经检查，我已经安装了1.0.0版本的causal-conv1d与1.0.1版本的mamba-ssm,
![图片](https://github.com/JCruan519/VM-UNet/assets/117566234/e0e0c02d-2e94-4ba4-a222-7ed52503a3fa)
![图片](https://github.com/JCruan519/VM-UNet/assets/117566234/629bee40-f47b-4430-bd2c-2e376589773b)

同时vmamba.py报红。
![图片](https://github.com/JCruan519/VM-UNet/assets/117566234/f5f96011-7d12-49a3-a69c-9cf6f430bdb1)
请问为何会报NameError: name 'selective_scan_fn' is not defined的错误呢

**Comment by xiaomengxin123** [comment]
+1

**Comment by DuHao55** [comment]
@JCruan519 Thank you so much for your prompt and detailed response.

**Comment by THTHK354** [comment]
> @xiaomengxin123 @DuHao55
> 
> Hello, please try to install following these steps:
> 
> 1. Choose a device with a Linux platform.
> 2. Ensure that your CUDA version is 11.8 or above, which can be checked by entering the command nvcc -V.
> 3. Download the relevant .whl installation package from the link: https://pan.baidu.com/s/1Uza8g1pkVcbXG1F-2tB0xQ?pwd=p3h9.
> 4. Uninstall the already installed packages causal_conv1d and mamba_ssm.
> 5. Use pip install to directly install the corresponding .whl file.

照您的方法操作了后，selective_scan依旧报红

**Comment by xiaomengxin123** [comment]
you can get it on the mamba official github realse and you will find it soon.

**Comment by feililucky** [comment]
Hello, I checked some official github, but I can’t seem to find the .whl corresponding to my version.

**Comment by csl1994** [comment]
@JCruan519 
I ensure that the cuda is 11.8, but it still can not find the selective_scan_fn.
Env: torch 2.1.0, cu118.
mamba: mamba_ssm-1.0.1+cu118torch2.1cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
causal_conv1d: causal_conv1d-1.0.0+cu118torch2.1cxx11abiFALSE-cp38-cp38-linux_x86_64.whl

How to solve it?

Thx!

**Comment by 7unahan** [comment]
I have same issue...

**Comment by JCruan519** [comment]
@csl1994 
Hello, I recommend using the following versions of torch:
torch==1.13.0 torchvision==0.14.0

**Comment by CosmoWood** [comment]
> @csl1994 Hello, I recommend using the following versions of torch: torch==1.13.0 torchvision==0.14.0

Hi I  think the key is make sure the whl's(casual_conv and mamba_ssm) torch version is the same as installed version of pytorch. As I think i should solve the problems.I got 12.4 cuda and 1.13 torch.I hope it helps people who is still met this problems

**Comment by 1774537072** [comment]
@JCruan519 你好，你提供的网盘失效了，现在我遇到了同样的问题，NameError: name 'selective_scan_fn' is not defined. Did you mean: 'selective_scan_flop_jit'?，我按照要求进行安装的但是还是报错，请问可以再提供一下链接吗

**Comment by hafsa390** [comment]
> @xiaomengxin123 @DuHao55
> 
> Hello, please try to install following these steps:
> 
>     1. Choose a device with a Linux platform.
> 
>     2. Ensure that your CUDA version is 11.8 or above, which can be checked by entering the command nvcc -V.
> 
>     3. Download the relevant .whl installation package from the link: https://pan.baidu.com/s/1Uza8g1pkVcbXG1F-2tB0xQ?pwd=p3h9.
> 
>     4. Uninstall the already installed packages causal_conv1d and mamba_ssm.
> 
>     5. Use pip install to directly install the corresponding .whl file.

Thanks @JCruan519 . Could you kindly provide another link with the relevant .whl installation package? Unfortunately, I am facing the 'selective_scan_fn' is not defined error and can not access to the packages due to not having Baidu account.

**Comment by ghost-baigao** [comment]
我使用了torch=1.1.3.1和torchvision=0.14，causal_conv1d=1.1.0，mamba_ssm=1.0.1，还是有这样的问题，我需要如何解决呢？之前causal_conv1d=1.0.0和mamba_ssm=1.0.1出现了RuntimeError: Expected u.is_cuda() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)这个问题，我需要如何解决？

**Comment by ghost-baigao** [comment]
本人小白，目前torch=1.13和torchvision=0.14，causal_conv1d=1.0.0，mamba=1.2.0，causal_conv1d和mamba_ssm都是用pip install whl文件安装的，现在还存在NameError: name 'selective_scan_fn' is not defined，需要怎么解决这个问题呢？
