### ISSUE TITLE
About Experiment's results

### ISSUE THREAD

**Issue by xiaomengxin123** [JCruan519/VM-UNet#12]
Excuse me, I follow your method and get results successfully，but I don't know how to use these results to get  this paper's evaluation indicators to know this model's power. So, will you update this github to show the model's result use?

**Comment by xiaomengxin123** [comment]
Sorry,  I find them in results' logs and thank you!

**Comment by xiaomengxin123** [comment]
Of course, because their results are in the logs and it's easy for you to find them in the latest log's end. Besides, the dataset's val or test just only one and the author made training and testing together in one code.

**Comment by anran0422** [comment]
@xiaomengxin123 你好，请问实验结果，你得出来的和论文一样吗。我按照Readme文档将环境配置好后，代码没有进行更改，按照步骤训练isic2018数据集，可是得到的结果并不像论文里那样的结果，不知道哪里出差错了！
![isic2018](https://github.com/user-attachments/assets/2a88fdcc-3c0e-4238-909a-5cb9334ef744)
