### ISSUE TITLE
weights link

### ISSUE THREAD

**Issue by Imenus247** [JCruan519/VM-UNet#15]
First and foremost, I would like to express my sincere gratitude for sharing your work; it is truly appreciated. However, I have encountered a challenge: accessing the network weights seems to be difficult from locations outside of China. Would it be possible to make them available on an alternative platform, such as Hugging Face, to facilitate access for an international audience? This would be extremely helpful for me and likely for other users as well.

**Comment by JCruan519** [comment]
@Imenus247 
Hello, thank you for your interest in our work. The pre-trained weights can now be downloaded via Google Drive at: https://drive.google.com/drive/folders/1Fr7zM1wq7106d0P7_3oeU5UZqUvk2KaP?usp=sharing
