### ISSUE TITLE
The depth of the network does not match the paper

### ISSUE THREAD

**Issue by shengyu27** [JCruan519/VM-UNet#19]
I have reviewed the pre training weights provided by the author and found that the depth is:
Small: [2,2,27,2] (downsampling)
Tiny: [2,2,9,2] (downsampling)
This is not consistent with [2,2,2,2] in the paper?

**Comment by JCruan519** [comment]
@shengyu27 
Hello, VM-UNet only utilizes partial pre-trained weights, which you can configure in config.py.
