### ISSUE TITLE
”pip install mamba_ssm==1.0.1“and"pip install causal_conv1d==1.0.0"  Report an error

### ISSUE THREAD

**Issue by wakakkakak** [JCruan519/VM-UNet#34]
Hello, I would like to ask the following error occurs when installing "pip install mamba_ssm==1.0.1",  and I wonder how to solve it?
I was running on a linux server.
When I type the command line:
![cuda](https://github.com/JCruan519/VM-UNet/assets/117575513/4042beeb-44ae-44f5-bf03-32cf574902ae)
When I type the command line:
![image](https://github.com/JCruan519/VM-UNet/assets/117575513/23b1500b-d5f7-4f81-9990-d80dc4a4425b)
When I type the command line:
![image](https://github.com/JCruan519/VM-UNet/assets/117575513/afacf634-99f7-4c81-a1fd-5999b1213e29)

I wonder what the problem is? And how to fix it?
I look forward to hearing from you!

**Comment by JCruan519** [comment]
@wakakkakak 
Hello, your CUDA driver needs to be upgraded to at least version 11.8 in order to use mamba_ssm.

**Comment by wakakkakak** [comment]
> @wakakkakak Hello, your CUDA driver needs to be upgraded to at least version 11.8 in order to use mamba_ssm.

Thank you for your replying! I
