### ISSUE TITLE
Training loss do not go down

### ISSUE THREAD

**Issue by fangxiao-yu** [JCruan519/VM-UNet#44]
Hello, I downloaded the source code and only modified bachsize to 16. However, during the training process, the training loss has not decreased. May I ask what caused this?
[train.info.log](https://github.com/JCruan519/VM-UNet/files/15026096/train.info.log)

**Comment by fangxiao-yu** [comment]
> 我也是，跟你遇到的情况一模一样，miou也很低

好离谱，你用的啥显卡啊，训练参数改了么

**Comment by ErinWang2023** [comment]
谢谢你哦！！

**Comment by fangxiao-yu** [comment]
> 我也是，跟你遇到的情况一模一样，miou也很低

@ErinWang2023 你用的啥显卡啊，训练参数改了么

**Comment by ErinWang2023** [comment]
> > 我也是，跟你遇到的情况一模一样，miou也很低
> 
> @ErinWang2023 你用的啥显卡啊，训练参数改了么

bachsize改成了20，其他参数都一样，用的是P100，16G的

**Comment by ErinWang2023** [comment]
> > > 我也是，跟你遇到的情况一模一样，miou也很低
> > 
> > 
> > @ErinWang2023 你用的啥显卡啊，训练参数改了么
> 
> bachsize改成了20，其他参数都一样，用的是P100，16G的

他提供的两个数据集我都跑了，Synapse跑完了dice只有0.0139,训练过程中loss也是在1.1上下徘徊

**Comment by fangxiao-yu** [comment]
如果不改bach size呢？我也改了我改成16了，因为我的显卡显存不够



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 23, 2024 19:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JCruan519/VM-UNet] Training loss do not go down (Issue #44)




    
我也是，跟你遇到的情况一模一样，miou也很低
  
@ErinWang2023 你用的啥显卡啊，训练参数改了么
  
bachsize改成了20，其他参数都一样，用的是P100，16G的
  
他提供的两个数据集我都跑了，Synapse跑完了dice只有0.0139,训练过程中loss也是在1.1上下徘徊

**Comment by ErinWang2023** [comment]
> 如果不改bach size呢？我也改了我改成16了，因为我的显卡显存不够
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Apr 23, 2024 19:09 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [JCruan519/VM-UNet] Training loss do not go down (Issue #44) 我也是，跟你遇到的情况一模一样，miou也很低 @ErinWang2023 你用的啥显卡啊，训练参数改了么 bachsize改成了20，其他参数都一样，用的是P100，16G的 他提供的两个数据集我都跑了，Synapse跑完了dice只有0.0139,训练过程中loss也是在1.1上下徘徊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

跑这个Synapse数据集的时候，什么参数都没改

**Comment by ErinWang2023** [comment]
我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来

**Comment by fangxiao-yu** [comment]
> 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来

@ErinWang2023 太奇怪了，实在想不出来是哪里的问题

**Comment by ErinWang2023** [comment]
> > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> 
> @ErinWang2023 太奇怪了，实在想不出来是哪里的问题

我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化

**Comment by fangxiao-yu** [comment]
> > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > 
> > 
> > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> 
> 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化

![image](https://github.com/JCruan519/VM-UNet/assets/62005360/d942b556-7307-46b8-ba78-06cb0af7116a)
我看了是对应的，我师兄也是这么跟我说的

**Comment by ErinWang2023** [comment]
> > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > 
> > > 
> > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > 
> > 
> > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> 
> ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的

那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。

**Comment by fangxiao-yu** [comment]
> > > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > > 
> > > > 
> > > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > > 
> > > 
> > > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的
> 
> 那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。
我师兄和导师也是这么说的

**Comment by ErinWang2023** [comment]
> > > > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > > > 
> > > > > 
> > > > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > > > 
> > > > 
> > > > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的
> > 
> > 
> > 那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。
> 
> 我导儿和师兄也是这么说的，那你还打算继续跑么，如果想继续研究的话，咱俩加个联系方式，方便交流

可以呀~wx嘛？

**Comment by fangxiao-yu** [comment]
> > > > > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > > > > 
> > > > > > 
> > > > > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > > > > 
> > > > > 
> > > > > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的
> > > 
> > > 
> > > 那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。
> > 
> > 
> > 我导儿和师兄也是这么说的，那你还打算继续跑么，如果想继续研究的话，咱俩加个联系方式，方便交流
> 
> 可以呀~wx嘛？

wx：____sunrain____

**Comment by fangxiao-yu** [comment]
> > > > > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > > > > 
> > > > > > 
> > > > > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > > > > 
> > > > > 
> > > > > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的
> > > 
> > > 
> > > 那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。
> > 
> > 
> > 我导儿和师兄也是这么说的，那你还打算继续跑么，如果想继续研究的话，咱俩加个联系方式，方便交流
> 
> 可以呀~wx嘛

直接搜13942571472

**Comment by fm52Hz** [comment]
> > > > 我也是，跟你遇到的情况一模一样，miou也很低
> > > 
> > > 
> > > @ErinWang2023 你用的啥显卡啊，训练参数改了么
> > 
> > 
> > bachsize改成了20，其他参数都一样，用的是P100，16G的
> 
> 他提供的两个数据集我都跑了，Synapse跑完了dice只有0.0139,训练过程中loss也是在1.1上下徘徊

朋友，这个问题解决了吗？我换了自己的数据集，发现也是这个情况。。

**Comment by ErinWang2023** [comment]
谢谢你哦！！

**Comment by fangxiao-yu** [comment]
> Hello, I downloaded the source code and only modified bachsize to 16. However, during the training process, the training loss has not decreased. May I ask what caused this? [train.info.log](https://github.com/JCruan519/VM-UNet/files/15026096/train.info.log)

**Comment by chjwhere** [comment]
> > > > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > > > 
> > > > > 
> > > > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > > > 
> > > > 
> > > > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的
> > 
> > 
> > 那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。
> 
> 我导儿和师兄也是这么说的，那你还打算继续跑么，如果想继续研究的话，咱俩加个联系方式，方便交流

你好，我也遇到了你所提及的问题。我的显卡跑不动batch size=32，因此我改为batch size=16。仅修改一处，其他代码没有动。训练Synapsse后测试结果mean Dice只有0.018，不知道是哪里出现了问题。请问你当时遇到的这种情况被解决了吗？是如何解决的？希望能与你交流，感激！

**Comment by chjwhere** [comment]
> > > > > > > 我也是因为显存不够才改的bachsize的，不改的话17.18这个数据集跑不起来
> > > > > > 
> > > > > > 
> > > > > > @ErinWang2023 太奇怪了，实在想不出来是哪里的问题
> > > > > 
> > > > > 
> > > > > 我组的师兄说，可能是数据和标签没有对齐导致的，让我在dataset.py这里打印出来看看，你试试看给我说哈哈哈，我还在跑17.18这个数据集，想跑完看看iou会不会好一点，反正现在loss没啥变化
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/62005360/324817164-d942b556-7307-46b8-ba78-06cb0af7116a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxMDcsIm5iZiI6MTcxMzg3MjgwNywicGF0aCI6Ii82MjAwNTM2MC8zMjQ4MTcxNjQtZDk0MmI1NTYtNzMwNy00NmI4LWJhNzgtMDZjYjBhZjcxMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ODU5OWYxM2U2ZTk0NGU0YmM2NTY4YTgwNDIxMGZlZTQwNmE0ODQwOWY2NmU3MzE3ZDFmMjQzMjk2ZDMyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-rnVxHALBAwnwCAQ7kNjPiE_znv19iVD6pMy-ZesX5M) 我看了是对应的，我师兄也是这么跟我说的
> > > 
> > > 
> > > 那就不知道哪里问题了，跑得起来，结果差距跟作者这么大，真的想不明白，我问了师兄会不会是显卡的问题，师兄说不太可能是显卡的问题。。。
> > 
> > 
> > 我导儿和师兄也是这么说的，那你还打算继续跑么，如果想继续研究的话，咱俩加个联系方式，方便交流
> 
> 可以呀~wx嘛？

你好，我也遇到了你所提及的问题。我的显卡跑不动batch size=32，因此我改为batch size=16。仅修改一处，其他代码没有动。训练Synapsse后测试结果mean Dice只有0.018，不知道是哪里出现了问题。请问你当时遇到的这种情况被解决了吗？是如何解决的？希望能与你交流，感激！

**Comment by Bougaivillea10** [comment]
@fangxiao-yu 你好，请问你的这个问题解决了吗，我也碰到了相同的问题，可以交流一下吗？

**Comment by ErinWang2023** [comment]
谢谢你哦！！
