### ISSUE TITLE
backbone中的特征尺度的疑问

### ISSUE THREAD

**Issue by SPECTRELWF** [JCruan519/VM-UNet#5]
作者您好，我在VManba论文中看到的四个尺度的特征图分别是下采样了4，8，16和32，但在您的代码中，我用feature_backbone求得的四个尺度的特征图分别下采样了8，16，32，32，请问一下这是为什么呢

**Comment by JCruan519** [comment]
@SPECTRELWF 

Hello, these are the sizes of the feature maps I printed, which are as follows:

torch.Size([2, 64, 64, 96])
torch.Size([2, 64, 64, 96])
torch.Size([2, 32, 32, 192])
torch.Size([2, 16, 16, 384])
torch.Size([2, 8, 8, 768])
torch.Size([2, 8, 8, 768])

The code used is:

```python
def forward_features(self, x):
    skip_list = []
    x = self.patch_embed(x)
    if self.ape:
        x = x + self.absolute_pos_embed
    x = self.pos_drop(x)
    print(x.size())

    for layer in self.layers:
        print(x.size())
        skip_list.append(x)
        x = layer(x)
    print(x.size())
    return x, skip_list
```

The printed results are consistent with Fig2 in the original paper.

**Comment by SPECTRELWF** [comment]
已解决，感谢回复
