### ISSUE TITLE
关于跳跃连接的问题

### ISSUE THREAD

**Issue by ChaohuanDeng123** [JCruan519/VM-UNet#58]
你好，在论文中H/4 * W/4 * C的特征图中有一次跳跃连接
但是我debug了代码，发现在

> https://github.com/JCruan519/VM-UNet/blob/acbafd5ad5b275a0ddee5a449e2adeeb2243d6a4/models/vmunet/vmamba.py#L734-L741
这部分的代码，inx最大只能到3，所以skip_list只能取到-3索引的值，其实第一个跳跃连接根本没用到。

希望作者解答疑惑

**Comment by Akutto** [comment]
我也发现了，应该只连了三次吧

**Comment by lwtgithublwt** [comment]
@ChaohuanDeng123 @Akutto 我也发现了，请问你们自己训练时是否加上，加上效果是否会变好，感谢告知！

**Comment by Akutto** [comment]
> 我也发现了，请问你们自己训练时是否加上，加上效果是否会变好，感谢告知！

好像他引用的vmamba也是三次，我还是照着三次没加

**Comment by JCruan519** [comment]
非常感谢指出这个问题！
我们会在下一个版的论文中改成这个错误。
再次表示感谢！！！

**Comment by acav485** [comment]
你好，请问你知道怎么把第一个跳跃连接加上吗？
