### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by 2962313771** [JCruan519/VM-UNet#7]
![image](https://github.com/JCruan519/VM-UNet/assets/114922961/0ca591ae-0fd1-43f2-94ad-4409abfd8a41)
这里有两个cuda版本，应该选择哪个呢，不能同时有两个吧

**Comment by 2962313771** [comment]
我在执行下面的句子的时候出现了很多错误，能不能推荐一个cuda版本

pip install causal_conv1d==1.0.0  # causal_conv1d-1.0.0+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl
pip install mamba_ssm==1.0.1  # mmamba_ssm-1.0.1+cu118torch1.13cxx11abiFALSE-cp38-cp38-linux_x86_64.whl

**Comment by ZhiQiangYang513** [comment]
在多次安装后，我认为cuda11.8是最低要求。

**Comment by JCruan519** [comment]
@2962313771 
You need to configure CUDA 11.8 in your environment to install and use the `causal_conv1d` and `mamba_ssm` libraries. For Torch-related libraries, simply follow the instructions mentioned above for installation.

**Comment by 2962313771** [comment]
OK,Thanks.

**Comment by niu-yq** [comment]
> 功

你好，我想问一下你的torch是哪个版本的

**Comment by hqzqaq** [comment]
我的torch是2.2.1的版本

**Comment by niu-yq** [comment]
你好，我在pytorch官网上看到的目前cuda只有12.1的版本，torch版本也有对应是2.2.1的，但是当我把cuda改成12.2就安装失败了，而torch2.2.1和cuda12.1又会出现这个报错，另外我还尝试了torch 2.0.0+cu118也是会有这个报错，可以问一下怎么下载torch12.2+cu122吗（我的mamba-ssm==1.2.0.post1 causal-conv1d==1.1.3.post1）






。。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JCruan519/VM-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月4日(星期四) 晚上7:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JCruan519/VM-UNet] cuda version (Issue #7)





 
我的torch是2.2.1的版本

**Comment by hqzqaq** [comment]
尝试一下这个命令吧
```sh
pip3 install torch torchvision torchaudio
```
我忘记我咋装的了，当时我装环境也卡了一下，后面很快解决了，忘记咋弄的了

**Comment by niu-yq** [comment]
好的，谢谢你！！！




。。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JCruan519/VM-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月4日(星期四) 晚上10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JCruan519/VM-UNet] cuda version (Issue #7)





 
尝试一下这个命令吧
 pip3 install torch torchvision torchaudio
 
我忘记我咋装的了，当时我装环境也卡了一下，后面很快解决了，忘记咋弄的了
