### ISSUE TITLE
Train on Synapse: loss doesn't decrease and got 0.018 Dice. 训练Synapse损失不降，测试dice为0.018

### ISSUE THREAD

**Issue by chjwhere** [JCruan519/VM-UNet#85]
I changed the batch size from 32 to 16 in order to make it work on my GPU. And nothing else in the source data was changed. But after it trained on Synapse, the test result was 0.018 for mean Dice. The loss kept around 1.1. Anybody meets this problem? What should I do? Thanks a lot!
我把batch size从32改为16后训练Synapse数据集，其他任何参数都没有修改，数据集也是按照要求下载的。训练时的损失在1.1左右，测试时得到的结果Dice只有0.018。有没有人也遇到这个问题。应该如何解决。非常感谢！

**Comment by chjwhere** [comment]
problem solved

**Comment by Narrator174** [comment]
你好,我也遇到了一样的问题,可以告诉我你是怎么解决的吗 @chjwhere

**Comment by Bougaivillea10** [comment]
我也是同样的问题

**Comment by ngodongnguyen** [comment]
> problem solved

can I ask you how you can solve this problem ?
The dice only 0,75
