### ISSUE TITLE
myNormalize' object has no attribute 'mean'

### ISSUE THREAD

**Issue by achuansztu** [JCruan519/VM-UNet#86]

**Comment by ljmkgbkq** [comment]
I have the same problem as you. How did you solve it?
Thank you very much~

**Comment by shendulcf** [comment]
> I have the same problem as you. How did you solve it? Thank you very much~

可能你是用的自己数据集？要去那个函数下面加自己数据集的正则化参数

**Comment by hz1z** [comment]
@ljmkgbkq @achuansztu 
你得在这添加你的数据集的一些参数

![Image](https://github.com/user-attachments/assets/6a5aab6e-8c34-49fe-8fc1-3f52c138f999)
